version: 2
jobs:
  test_213:
    working_directory: /code
    docker:
        - image: openjdk:11
        - image: jboss/keycloak:latest
          environment:
            KEYCLOAK_USER: "admin"
            KEYCLOAK_PASSWORD: "admin"
    environment:
      - SBT_VERSION: 1.3.8
    steps:
      - run:
          name: Install SBT
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y sbt git
            apt-get clean && apt-get autoclean
      - checkout
      - run:
         name: Install Dockerize
         command: |
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
         environment:
           DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for Keycloak Server
          command: dockerize -wait tcp://localhost:8080 -timeout 5m
      - run:
          name: Run Tests
          command: sbt ++2.13.1! test
      - run:
          name: Upload Reports
          command: |
            bash <(curl -s https://codecov.io/bash)
  test_212:
    working_directory: /code
    docker:
      - image: openjdk:11
      - image: jboss/keycloak:latest
        environment:
          KEYCLOAK_USER: "admin"
          KEYCLOAK_PASSWORD: "admin"
    environment:
      - SBT_VERSION: 1.3.8
    steps:
      - run:
          name: Install SBT
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y sbt git
            apt-get clean && apt-get autoclean
      - checkout
      - run:
          name: Install Dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for Keycloak Server
          command: dockerize -wait tcp://localhost:8080 -timeout 5m
      - run:
          name: Run Tests
          command: sbt ++2.12.10! clean coverage test coverageReport
      - run:
          name: Upload Reports
          command: |
            bash <(curl -s https://codecov.io/bash)
  Publish-And-Release:
    docker:
      - image: circleci/openjdk:latest
      - image: jboss/keycloak:latest
        environment:
          KEYCLOAK_USER: "admin"
          KEYCLOAK_PASSWORD: "admin"
    working_directory: ~/code
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-0
      - run:
          name: Import PGP Key
          command: |
            sudo rm -rf /var/lib/apt/lists/* && sudo apt-get update
            sudo apt-get install -y dos2unix
            echo -e "$PGP_KEY" > key.asc
            dos2unix key.asc
            gpg --import key.asc
      - run:
          name: Compile JAR
          command: sbt 'release with-defaults'
      - run:
          name: Upload Reports
          command: |
            bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: sbt-cache-0
          paths:
            - "~/.m2"
            - "~/.sbt"
            - "~/.ivy2/cache"
workflows:
  version: 2
  deployment:
    jobs:
      - test_212
      - test_213
      - Publish-And-Release:
          filters:
            branches:
              only:
                - master